# Generated by Django 5.1.3 on 2024-11-10 09:15

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images', variations={'large': (600, 400), 'medium': (300, 200), 'thumbnail': (100, 100, True)}),
        ),
    ]
