# Generated by Django 5.1.3 on 2024-11-18 02:41

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images', variations={'large': (600, 400), 'medium': (350, 250), 'thumbnail': (100, 100, True)}),
        ),
    ]
