# Generated by Django 5.1.3 on 2024-11-25 02:21

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='uploads/images', variations={'medium': (350, 250), 'thumbnail': (100, 100, True)}),
        ),
    ]
