# Generated by Django 5.1.3 on 2024-11-25 03:47

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_comment_post_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images', variations={'medium': (350, 250), 'thumbnail': (100, 100, True)}),
        ),
    ]
